### ISSUE TITLE
@constant_pool_test.cc: testing int, long, byte, string

### ISSUE THREAD

**Issue by ccebinger** [ccebinger/SWPSoSe14#100]
Tests für folgende Datentypen erstellen:
- Byte
- Int
- Long
- String

Zusätzlich prüfen, ob 

```
check()
```

ausgeführt wird.

**Comment by ccebinger** [comment]
Prinzipiell für Strings jetzt implementiert.

**Comment by mbaeten** [comment]
was ist hiermit?

**Comment by ChrisKujawa** [comment]
sinnloses ticket...
