### ISSUE TITLE
Add Name-type index to constant pool

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#110]
The value of the name_and_type_index item must be a valid index into the constant_pool table. The constant_pool entry at that index must be a CONSTANT_NameAndType_info structure. This constant_pool entry indicates the name and descriptor of the field or method. [1]

[1] http://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.4.2

**Comment by kretzschi** [comment]
Done
