### ISSUE TITLE
add Object ref and this class to ClassfileWriter 

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#111]
Object Ref means a CP entry for java/lang/Object.

Should be the first entry in CP.

**Comment by vincentbohlen** [comment]
Das könnte tricky sein.
Wir wollen ja eine MethodRef an die erste Stelle schreiben, die aber die ClassRef braucht, die dahinter stehen soll. Die darf aber auch nicht direkt dahinter stehen, weil wir an zweiter Stelle die FieldRef auf java/lang/System brauchen (oder?)

**Comment by kretzschi** [comment]
Kann es zwar nicht mit Bestimmtheit sagen, aber im Prinzip ist es egal. Hauptsache die Referenzen stimmen und die Typen sind richtig definiert.
