### ISSUE TITLE
add descriptor () V to ClassFileWriter

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#117]
Beim Schreiben des ersten Elements in den CP ("java/lang/Object"), wird ein "Name_and_Type" definiert. Dabei ist der Name "" und der Typ "()V".

Diesen Typ "void" also "()V" wollen wir zunächst für alle Rail Funktionen benutzen, da erst in MS3 geklärt werden muss, wie Argumente in Rail im JavaByteCode representiert werden sollen (siehe dazu #118)

**Comment by vincentbohlen** [comment]
Steht drin, oder?
Line 161 constant_pool.cc

**Comment by kretzschi** [comment]
Ja.
