### ISSUE TITLE
Create global stack

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#118]
The current stack is only available for each method, but in rail the stack is global.

Another function can read values from the stack which was pushed from another.

**Comment by jdettlaff** [comment]
Nutzen ArrayDeque. (Wenig Overhead: keine Synchronisierung, kein übermäßiger Platzoverhead) Implementierung folgt in Kürze.

**Comment by kretzschi** [comment]
Wie siehts aus?

**Comment by mbaeten** [comment]
in unserer Mail wird jetzt auch mit -o die out-file angegeben

**Comment by jdettlaff** [comment]
Grade gemerkt, dass wir dafür nicht nur push/pop, sondern jede Stackoperation ändern müssen ;) Bau ich noch ein.

**Comment by kretzschi** [comment]
Könntest du wenigstens schon einmal eine Schnittstelle rausgeben? Wir stocken gerade ein bisschen ...

**Comment by jdettlaff** [comment]
Jo gepusht in classfix, im BytecodeGenerator: Funktionen globalstack_push und globalstack_pop. Diese Version generiert dann auch keinen Bytecode, also existierendes sollte nicht kaputtgegangen sein ;)

**Comment by jdettlaff** [comment]
Mostly done. Remainder in separate tickets. Closing this.
