### ISSUE TITLE
test long datatype in Rail

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#119]
Es soll überprüft werden, was beim Rechnen mit riesigen Zahlen in Rail passiert.

**Comment by kretzschi** [comment]
Also, der rail Interpreter verhält sich wie in bspw. Java. 
D.h. er rechnet mit Integer der Größe -2147483648 bis 2147483647. Zum Beispiel habe ich durchgespielt:
- [2147483647][1]ao-# ergibt -2147483648
- [2147483647][4]mo-# ergibt -4
  usw.

Wir müssten also festlegen, ob wir intern beim Rechnen mit Ints über / unter 2147483647 / -2147483648 im CP Longs hinzufügen, oder eben das Verhalten 1 zu 1 übersetzen (als dann auch mit den Überläufen).

**Comment by kretzschi** [comment]
Wir übernehmen das Verhalten von Rail beim Rechnen mit großen Zahlen (siehe oben).
Done.
