### ISSUE TITLE
check method to write hex values

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#122]
Die Werte die zurzeit gespeichert werden sind glaube nicht alle korrekt und das liegt meiner Meinung nach dadran das sie nicht als hex gespeichert werden oder etwas zu kurz (zb fehlen nullen)

Dies muss angepasst werden damit die Classfile funktioniert

**Comment by ChrisKujawa** [comment]
z.b. eine variante:

<pre>
std::stringstream sstream;
sstream.fill('\x0');
sstream.width(2);
sstream /</< std::hex /</< value;
</pre>

**Comment by ChrisKujawa** [comment]
http://www.cplusplus.com/articles/DzywvCM9/

**Comment by ChrisKujawa** [comment]
Mit Bytecode_writer write method funktioniert auch das tag schreiben! (vorher gabs probleme mit stringstream)
#108

**Comment by mbaeten** [comment]
@Zelldon was ist mit cstdint? das hatte ich jetzt überall verwendet. Ist das nicht das selbe?

**Comment by ChrisKujawa** [comment]
Jaein in der header sind ja nur die typedefs definiert aber net die umrechnung nach big endian usw oder was meinst du

**Comment by mbaeten** [comment]
ajo ok, das war mir nicht bewusst, danke (hatte den artikel nur überflogen)

**Comment by vincentbohlen** [comment]
deine klasse funkioniert doch super. kann man schließen, oder?

**Comment by ChrisKujawa** [comment]
Wollt evtl noch bissel erweitern aber bist zufrieden ja? XD guck mal constant Pool dir an hab den veraendert

**Comment by kretzschi** [comment]
filestream.write(reinterpret_cast<char*> (bytes) , bsize); (line 21)

invalid cast from type ‘std::vector<unsigned char>’ to type ‘char*’

**Comment by ChrisKujawa** [comment]
Wieso bekomm ik diese fehler net.. Btw mauricw hat diesen cast geadded aber ich guck mal morgen

**Comment by vincentbohlen** [comment]
&bytes löst den Fehler. kA obs auch funktioniert. Ist ja mal wieder kaputt ^^

**Comment by ChrisKujawa** [comment]
ja also habs in (char*) &bytes[0] geaendert
