### ISSUE TITLE
Constantpool should use wrapper classes not primitive types

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#123]
We can't handle the primitive data types like int, because for the typecheck in the bytecode_generator, we need the Wrapper Classes (e.g. java/lang/Integer)

**Comment by vincentbohlen** [comment]
Was ist hier jetzt noch genau zu tun?
Bin momentan arbeitslos (bis die check funktioniert und wieder neue bugs kommen^^)

**Comment by ChrisKujawa** [comment]
Kannst mal gucken vorhin ging die check methode dann :)

**Comment by ChrisKujawa** [comment]
Brauchen wir ueberhaupt die addInt methode im Constantpool? Eig net oder

**Comment by mauriceAlthoff** [comment]
um integer konstanten zu pushen

**Comment by mauriceAlthoff** [comment]
scheinbar brauchen wir das nicht
