### ISSUE TITLE
WriteSuperClassName and WriteClassName create wrong reference types

### ISSUE THREAD

**Issue by kretzschi** [ccebinger/SWPSoSe14#124]
At the moment they create CONSTANT_UTF8 (strings) but should create CONSTANT_CLASS instead.

**Comment by vincentbohlen** [comment]
void ClassfileWriter::WriteClassName() {
    uint16_t str = constant_pool_->addString("Main");
    std::cout << str;
    writer.writeU16(constant_pool_->addClassRef(constant_pool_->addString("Main")));
}

<b>funktioniert. Dann schreibt er auch korrekt WriteSuperclassName();</b>

void ClassfileWriter::WriteClassName() {
    writer.writeU16(constant_pool_->addClassRef(constant_pool_->addString("Main")));
}

<b>funktioniert weder WriteClass noch WriteSuperClass</b>

**Comment by vincentbohlen** [comment]
funktioniert jetzt in der gesamten ausführung.

**Comment by vincentbohlen** [comment]
Allerdings sind die werte falsch.....

**Comment by kretzschi** [comment]
Was stimmt genau nicht ?

**Comment by ChrisKujawa** [comment]
also das liegt am Constant pool weil der iwie immer neues item pushed bei den classes wenn die nochmal auftauchen
