### ISSUE TITLE
putUTF8 in CP should return index in CP

### ISSUE THREAD

**Issue by kretzschi** [ccebinger/SWPSoSe14#128]
putUTF8 returns void at the moment but should return the index of the CONSTANT_UTF8 element in the CP

**Comment by mauriceAlthoff** [comment]
ne, sollte es nicht da es eine interne Funktion ist und einen utf8 string erstellen soll und in den pool pushen. So funktionieren auch die anderen push Funktionen

**Comment by vincentbohlen** [comment]
addString ruft putUTF8 auf und returned dann den index, wenn ich das richtig sehe.

**Comment by kretzschi** [comment]
Ahja, sry. Die addString war mir gerade entfallen. Danke sehr! :)
