### ISSUE TITLE
Issues Organisieren

### ISSUE THREAD

**Issue by hanintalal** [ccebinger/SWPSoSe14#129]
Wir hatten einen Problem beim Git ,deshalb wurde alle issues noch mal geoeffnet .
bitte alle issues ,die bereit gemacht wreden ,schliessen ,damit wir genau wissen ,was fehlt noch .
ich habe das hier schrieben muessen ,weil man manschmal email uebersieht .
Danke

**Comment by mbaeten** [comment]
Was meinst du damit? Sieht nicht so aus, als wären alle Issues wieder offen: 54 open/ 75 closed
