### ISSUE TITLE
Attribute schreiben für Methoden außer main und init

### ISSUE THREAD

**Issue by vincentbohlen** [ccebinger/SWPSoSe14#131]

**Comment by kretzschi** [comment]
Nur init hat "feste" Attribute.

Heikel wird nur, den Graphen so zu "synchronisieren", dass wir für jede Methode die richtigen Befehle in Bytecode generieren.

**Comment by kretzschi** [comment]
Ich verweise mal auf Issue #132, da ich das schreiben der Attribute generisch mache und somit unabhängig der methode wird. Closed.
