### ISSUE TITLE
Attribute schreiben für main und init

### ISSUE THREAD

**Issue by vincentbohlen** [ccebinger/SWPSoSe14#132]

**Comment by kretzschi** [comment]
Brauchen eigentlich kein eigenes Ticket für die main, da wir den Code auch über den bytecode_generator generieren.

**Comment by vincentbohlen** [comment]
Ich habe halt das Ticket  #17 in Milestone 1 geschlossen und in #132 in M2 und #131 in M3 geteilt. Einfach der Ordnung wegen.

**Comment by vincentbohlen** [comment]
Es gibt noch ein paar wenige Punkte, die nicht richtig fuktionieren, aber zusammenhängen.
In der generierten Classfile sind noch falsch:

attribute length
max_stack
code_length
code

Das ist alles im attribute part der methoden.
Gerade das code nicht richtig ist, ist beunruhigend.
Wenn das passt, dann ist die classfile fertig.

So sieht die Methode jetzt aus:
09 | 00 18 | 00 0A  | 00 01 | 00 08 | 00 00 00 <b>14</b> | ?? ?? | 00 01 | 00 00 00 <b>08 | 12 00 2F 4C B2 2B B6 B1 </b> | 00 00 | 00 00

So soll sie aussehen:
09 | 00  18 | 00  0A | 00 01 | 00 08 | 00 00 00 15 <b>| <i>00 02</i></b> |  00 01 | 00 00 00 09 | B2 00 2E 12 30 B6 00 28 B1 |  00 00 | 00 00
(00 02 fehlt in der erzeugten. das ist max stack)

**Comment by kretzschi** [comment]
Also, die erzeugten Bytes vom Code waren ja:
12  4c  b2  2b  b6  b1 (LDC -> ASTORE_1 -> GET_STATIC -> ALOAD_1 -> INVOKE_VIRTUAL -> RETURN)

Normalerweise: GET_STATIC -> u2 CP-REF -> LDC -> u1 CP-REF -> INVOKE_VIRTUAL -> u2 CP_REF -> RETURN

Also scheinbar werden die falschen Methoden im generator aufgerufen. Müsste so aussehen:

push_Bytes(...)
output_Bytecode(...)
|
--- add_static_field(...)
--- add_invoke_virtual(...)

**Comment by vincentbohlen** [comment]
Wir sehen, dass deie attributgenerierung funktioniert. jetzt is die arbeit im bytecode_generator zu tun, Deswegen close und ich eröffne ein neues issue.

**Comment by vincentbohlen** [comment]
#146
