### ISSUE TITLE
check method in constant pool is not working

### ISSUE THREAD

**Issue by vincentbohlen** [ccebinger/SWPSoSe14#139]
always returns false.
most likely because std::find compares object adresses, not values?

**Comment by vincentbohlen** [comment]
im akuten Fall werden falsche indizes für Klassen zurückgegeben.
Bin mit meinem Latein jetzt am Ende

**Comment by ChrisKujawa** [comment]
Naja das problem ist bei den class items das die attribute name_idx dann nach dem schreiben beim naechsten vergleich wieder 0 ist

**Comment by vincentbohlen** [comment]
funktioniert jetzt blendend =) richtig laser! ;)
