### ISSUE TITLE
Attributes: (global) counting of max stack items

### ISSUE THREAD

**Issue by kretzschi** [ccebinger/SWPSoSe14#140]
For the code attribute we have to count the maximum depth of operand stack in the bytecode_generator 

http://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.7.3 #131 #132

**Comment by jdettlaff** [comment]
Doesn't need to be much since we'll be using a global stack object on 
the heap.

Am 15.06.2014 09:53, schrieb kretzschi:

**Comment by kretzschi** [comment]
Thus, I'll assign the issue to you :P
You have to provide the number for the classfile_writer

**Comment by jdettlaff** [comment]
After a lot of thinking: TEN! Now i just need to know where to put that number.

**Comment by jdettlaff** [comment]
Set to 20. Just to be safe.
