### ISSUE TITLE
Strings korreckt unmarshallen

### ISSUE THREAD

**Issue by vincentbohlen** [ccebinger/SWPSoSe14#145]
Derzeit wird noch [Hello World!\n] ausgelesen. Es sollte natürlich Hello World!\n sein.

**Comment by mbaeten** [comment]
Das muss zwischen ASG und Backend passieren, sonst müssen unmarshall und marshall beide angepasst werden (unnötig). Das sollte im besten Fall trotzdem jemand aus dem Frontend machen

**Comment by jdettlaff** [comment]
Dies gilt auch für Variablennamen - sollte als Argument im Command nur _varname_ statt (!_varname_!) oder (_varname_) haben.

**Comment by mbaeten** [comment]
Betrifft das auch Methodenaufrufe {foo} ?
Ja wie gesagt 2 Möglichkeiten:
1. Wir passen Parser, marshall und unmarshall an
2. Ihr entfernt den Spass an einer Stelle im Backend

Ich bin stark für 2. und ich würds euch auch bauen. Dann müsst ihr mir nur mal sagen wo genau der Code für die 2-3 Sachen ist

**Comment by jdettlaff** [comment]
Das betrifft alle Argumente von Rail-Befehlen - also auch Methodenaufrufe - wir brauchen halt allgemein nur den String ohne das Rail-Gedöns.
Es reicht eine Methode (ich schlage einfach mal vor in backend.cc oder der Graphs-Klasse oder direkt der Command-Klasse) die zu einem Command den Argument-String ohne den Rail-Ballast zurückgibt. Und idealerweise direkt escapte Zeichen (\n) mit umwandelt.

**Comment by leonbornemann** [comment]
Hiho,

Eigentlich wollte ich das gestern schon fertig haben, leider hab ich es 
nicht mehr geschafft - sorry dafür ich mache es heute Abend/Nacht fertig.

Grüße,
Leon

Am 21.06.2014 13:50, schrieb jdettlaff:

**Comment by leonbornemann** [comment]
Die funktion ist geschrieben - ich habe sie erstmal bei graphs.ccp hinzugefügt.
Funktionsname: "extractAstCommandString" kriegt ein command übergeben und liefert den command-string ohne Rail-Gedöns (geiles Wort) zurück.

**Comment by ChrisKujawa** [comment]
Ich habs mal ins Command struct verschoben im Graphs machts wenig Sinn. Zudem dann noch mal angepasst das die ]Hello[ auch entfernt werden.
