### ISSUE TITLE
bytecode_generator überarbeiten

### ISSUE THREAD

**Issue by vincentbohlen** [ccebinger/SWPSoSe14#146]
Wir haben ein Problem mit der derzeitigen ausführung des bytecode_generator.
Wir gehen den graphen linear durch und pushen die jeweiligen Befehle auf den Stack.
Dabei beachten wir aber die ausführungsreihenfolge nicht.
Im konkreten Hello World beispiel ergibt sich daraus folender Fehler:

Wir lesen und schreiben momentan etwa so etwas:

opcode [12] - 0000: ldc 48 [String: [Hello World\n]]
opcode [B2] - 0002: getstatic 46 [Fieldref: java.lang.System.out, type = java.io.PrintStream]
opcode [B6] - 0005: invokevirtual 40 [Methodref: java.io.PrintStream.println, parameter = (java.lang.String), returns = void]
opcode [B1] - 0008: return

daher liegt auf dem stack von unten nach oben
string
printStream
println

Was wir aber brauchen ist:

printStream
string
println

Das bekommen wir aber nur, wenn wir vor dem string push wissen, dass danach der string output folgt.

Wahrscheinlich muss die parserichtung rückwärts laufen.
Dann lesen wir output und können erstellen:
push PrintStream;
calculate_what_to_print();
push println;

und in der calculate_what_to_print(); wird der graph dann weiter iteriert.

das geht aber auch nicht wenn im file z.B. -----['a']--['b']-----o-o--# steht

**Comment by ChrisKujawa** [comment]
Naja das wuerde ich denke nicht machen weil was machste wenn addition oder sonst was da liegt? 

Ich denke wenn wir den globalen Stack von Jonas als attribut haben verfliegt diese Problem eh, da
wir unsere Values dann in diesem Stack haben.

**Comment by vincentbohlen** [comment]
Ja, dann müssten wir den nur langsam mal zur verfügung haben ^^

**Comment by vincentbohlen** [comment]
Ich habe mir mal die output_bytecode() methode vorgenommen und überarbeitet. So müsste das ganze aussehen. 

  uint16_t field_system_idx = BytecodeGenerator::add_field("java/lang/System", "out", "Ljava/io/PrintStream;", constantPool);
  BytecodeGenerator::add_static_field(field_system_idx, constantPool, result);
  uint16_t field_stack_idx = BytecodeGenerator::add_field("Main", "stack", "Ljava/util/ArrayDeque;", constantPool);
  BytecodeGenerator::add_static_field(field_stack_idx, constantPool, result);
  uint16_t pop_idx = BytecodeGenerator::add_method("java/util/ArrayDequeue", "pop", "()Ljava/lang/Object;", constantPool);
  BytecodeGenerator::add_invoke_virtual(pop_idx, constantPool, result);
  uint16_t toString_idx = BytecodeGenerator::add_method("java/lang/Object", "toString", "()Ljava/lang/String;", constantPool);
  BytecodeGenerator::add_invoke_virtual(toString_idx, constantPool, result);
  uint16_t println_idx = BytecodeGenerator::add_method("java/io/PrintStream", "println", "(Ljava/lang/String;)V", constantPool);
  BytecodeGenerator::add_invoke_virtual(println_idx, constantPool, result);

An @jdettlaff: Was würde bei deiner globalstack_pop noch anderes dazukommen? Reicht das nicht so?

**Comment by jdettlaff** [comment]
Hi hab die globalstack_pop() eben implementiert, die trägt auch Dinge bei Bedarf in den ConstantPool ein die nicht da sind. Sollte also in jedem Fall reichen.

**Comment by vincentbohlen** [comment]
nein tut sie nicht, denn der constantpool ist zu dem zeitpunkt schon geschrieben. es erscheint nur das n der classfile im CP, was im CP constructor gesetzt wird.
ich habe deine methode aber trotzdem gerne benutzt.

**Comment by ChrisKujawa** [comment]
habe mal noch nen struct hinzugefuegt fuer ArrayDeque das die indicies speichert - pop und push dabei angepasst (done)
