### ISSUE TITLE
Create and initialize the static ArrayDeque "stack" field in class file

### ISSUE THREAD

**Issue by jdettlaff** [ccebinger/SWPSoSe14#150]
**For the global stack we need to initialize the stack static field:**
    public static java.util.ArrayDeque stack;
    Signature: Ljava/util/ArrayDeque;
    flags: ACC_PUBLIC, ACC_STATIC

**static init code (method <clinit>) like:**
    static {};
    Signature: ()V
    flags: ACC_STATIC
    Code:
    stack=2, locals=0, args_size=0
    0: new           #2                  // class java/util/ArrayDeque
    3: dup
    4: invokespecial #3                  // Method java/util/ArrayDeque."<init>":()V
    7: putstatic     #4                  // Field stack:Ljava/util/ArrayDeque;
    10: return

**Needed in constant pool:**
    Classref: java/util/ArrayDeque
    Methodref: java/util/ArrayDeque."<init>":()V
    Fieldref: Main.stack:Ljava/util/ArrayDeque;
    UTF8: <clinit>

**Comment by vincentbohlen** [comment]
also ich habe jetzt quasi folgende Zeile im Constantpool umgesetzt:

public static ArrayDeque stack = new ArrayDequeu();

welchen Datentyp soll der stack noch bekommen?
Das ist wichtig für die < clinit > methode.
Ich nehme an char oder string?

**Comment by kretzschi** [comment]
So, ging schneller als gedacht. Also alle Field-Variablen in Java sind vom Type **CONSTANT_FieldRef**. Die Struktur im CP:

[15] CONSTANT_FieldRef  class_index=16  name_and_type_index=43 

Der class_index ist für alle Fields gleich, es ist ein Eintrag vom Typ **CONSTANT_Class** mit einem name_index, der immer (ja für alle Fields ob privat, public, static, ...) auf ein **CONSTANT_Utf8  bytes="Field"** zeigt.

Also, im Falle von public static ArrayDeque stack = new ArrayDeque(); als Field steht folgendes im CP:

/\* CP begin _/
[15] CONSTANT_Fieldref class_index=16; name_and_type_index=52
[16] CONSTANT_Class name_index=53
...
[28] CONSTANT_Utf8 length=5; bytes="stack"
[29] CONSTANT_Utf8 length=22; bytes="Ljava/util/ArrayDeque;"
...
[52] CONSTANT_NameAndType name_index=28; descriptor_index=29
[53] CONSTANT_Utf8 length=5; bytes="Field"
...
/_ CP end */

Soo, und im eigentlich Fieldteil der classfile, sieht es ähnlich wie bei den Methoden aus. Hier aus der Doku:
field_info {
    u2             access_flags;
    u2             name_index;
    u2             descriptor_index;
    u2             attributes_count;
    attribute_info attributes[attributes_count];
}
http://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.5

Im obigen Beispiel also:
/\* Field[6] \* _/
00 09   /_ u2 access_flags=9 _/
00 1C  /_ u2 name_index=28, length=5; bytes="stack" _/
00 1D  /_ u2 descriptor_index=29, length=22; bytes="Ljava/util/ArrayDeque;" _/
00 00   /_ u2 attributes_count=0 */

Wenn es noch Unklarheiten gibt, dann fragt :)

**Comment by vincentbohlen** [comment]
schreibe ich morgen noch dazu. jetzt will ich auch ins bett.

**Comment by kretzschi** [comment]
@Vincent: Gerade habe ich erst deinen Kommentar davor gelesen. Wenn die ArrayQueue von einem bestimmten Typ sein soll, dann bekommt das Field noch das **Signatur Attribut** hinzu.
Dieses hat die Form:

Signature_attribute {
    u2 attribute_name_index;
    u4 attribute_length;
    u2 signature_index;
}
http://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.7.9

Dafür muss im CP noch ein **CONSTANT_Utf8** für "Signatur" angelegt. Dieses Attribut ist dafür zuständig, festzulegen, welcher generische Typ für ArrayDequeue benutzt wird. Auf diesen Typ wird in den Attribute bytes gezeigt. Ein Eintrag sieht dann für String so aus:

**[10] CONSTANT_Utf8 length=42; bytes="Ljava/util/ArrayDeque<Ljava/lang/String;>;"**

Das Field-Attribut  im Ganzen sähe dann so aus:

00 01                     /\* u2 attributes_count=1 _/
00 09                     /_ u2 attribute_name_index=9, length=9; bytes="Signature" _/
00 00 00 02           /_ u4 attribute_length=2 _/
00 0A                     /_ Attribute bytes: */
