### ISSUE TITLE
'[' als Valid string parsen

### ISSUE THREAD

**Issue by hanintalal** [ccebinger/SWPSoSe14#151]

**Comment by KosticS** [comment]
Du meinst das Escaping, oder ? 
Also dass auch Strings wie '-----[hello world \] /n/]--o' geparst werden. 

Denn Strings wie '---[hello world [ { } < > /n/]--o' können bereits gepars werden :)

**Comment by mbaeten** [comment]
Esolang: "The '\' is used for quoting in a way similar to C (but palindromically). '\', '[', ']', newlines, and tabs must be quoted by '\', '\[\', '\]\', '\n\', or '\t\', respectively."

Dementsprechend sollte das Beispiel wie du es grade beschrieben hast garnicht gehen. Zumindest das hier nicht: ----[hello [ world]--- müsste ----[hello \[\ world]--- sein, sonst Fehelr

und das hier sollte momentan noch garnicht klappen: ----[abc\]\def]----

**Comment by ChrisKujawa** [comment]
Super waere wenn Ihr dann auch die '\' entfernt die zum Escaping von tab und newline benutzt werden. (Ist mir beim Hello World Test aufgefallen...)

**Comment by mbaeten** [comment]
das müsste dann auch die methode von leon leisten hinterm AST. im AST muss immer das stehen, was auch serialisiert/deserialisiert werden muss.

**Comment by ChrisKujawa** [comment]
Ja na mir is egal wie wollt nur anmerken das das noch nicht so ist ^^

**Comment by leonbornemann** [comment]
Werde mich drum kümmern hab für das escaping nochmal nen extra ticket aufgemacht, weil mir da auch noch unklar ist wie einige sachen funktionieren sollen: #188

**Comment by hanintalal** [comment]
@leonbornemann  : ich kann dabei helfen ,wenn du am Mittwoch an der uni 12-14 bist
du kennst schon den Parser sehr gut und ich interessiere mich sehr mehr zu lernen :) 
ich war letzten Mittwoch nicht da , weil ich zu beschäftigt war :+1:

**Comment by leonbornemann** [comment]
#188 hat das hier mit eingeschlossen
