### ISSUE TITLE
impl ArrayDeque pop method

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#154]

**Comment by ChrisKujawa** [comment]
#156 should be cast

**Comment by jdettlaff** [comment]
Warum cast?

**Comment by ChrisKujawa** [comment]
Weil wir die Values als objects in die Deque speichern und beim rausholen wieder casten muessen

**Comment by jdettlaff** [comment]
Sorry wenn ich verwirrt bin aber es gibt im Bytecode doch keine Casts, 
du kannst doch nur schauen ob eine Objectref zu einer bestimmten Class 
gehört mit checkcast. Aber wofür muss pop wissen was für ein Object 
geholt wird?

**Comment by ChrisKujawa** [comment]
Weil wir im ArrayDeque kein Typ angeben ergo speichern wir nur Objects d.h. um dann mit den Values wieder arbeiten zu koennen muessen wir es nach dem rausholen wieder casten mithilfe von checkcast (hab es mal als beispiel impl. Integer i = (Integer) obj; da wurde dann auch checkcast benutzt^^ komischer name fuer den cast... )

**Comment by jdettlaff** [comment]
Aber es ist kein Cast, es gibt keine Casts, es gibt doch nur Referenzen 
auf Objects. checkcast verändert nichts an der Object reference. Es 
prüft nur ob die Referenz auf ein Object des angegebenen Typs zeigt... 
ich glaube das muss ich mir gleich nochmal im Chat erklären lassen. 
Komme dann online...
