### ISSUE TITLE
fix append Bug

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#163]
use: Tests/test-cases2/append.txt

<pre>

$ java Main
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    Main.main([Ljava/lang/String;)V @34: invokevirtual
  Reason:
    Type uninitialized 30 (current frame, stack[1]) is not assignable to 'java/lang/StringBuilder'
  Current Frame:
    bci: @34
    flags: { }
    locals: { '[Ljava/lang/String;', 'java/lang/Object', 'java/lang/Object' }
    stack: { uninitialized 30, uninitialized 30 }
  Bytecode:
    0000000: b200 4512 48b6 0042 b200 4512 48b6 0042
    0000010: b200 45b6 0041 4cb2 0045 b600 414d bb00
    0000020: 4b59 b600 4e2b b600 522c b600 52b6 0053
    0000030: b600 42b2 0044 b200 45b6 0041 b600 43b6
    0000040: 0039 b1                                

        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2570)
        at java.lang.Class.getMethod0(Class.java:2813)
        at java.lang.Class.getMethod(Class.java:1663)
        at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
</pre>

**Comment by ChrisKujawa** [comment]
Warum nicht einfach String.concat benutzen ?!

**Comment by vincentbohlen** [comment]
ich bin gerade dabei

**Comment by vincentbohlen** [comment]
funktioniert auch schon, aber unsere constant_pool:addConstString macht fehler

**Comment by ChrisKujawa** [comment]
alles klar sag wenn hilfe brauchst ansonsten guck ich erstmal nach weiteren bugs

**Comment by vincentbohlen** [comment]
guck lieber weiter.

**Comment by vincentbohlen** [comment]
jetzt hast du den classfix gelöscht? wie bekomme ich die sachen jetzt in den master, wenn ich lokal noch auf classfix arbeite?

**Comment by ChrisKujawa** [comment]
ja na hab doch gestern schon gesagt ihr sollt auf dem master arbeiten ^^ kannst das glaube commiten dann git checkout master machen und dann mergen mit deinem classFix branch
