### ISSUE TITLE
Bytecode for Junctions

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#167]

**Comment by ChrisKujawa** [comment]
@mauriceAlthoff  Extrem wichtig! Bitte so schnell wie Moeglich.

**Comment by ccebinger** [comment]
Kann ich das übernehmen?

**Comment by kretzschi** [comment]
We need a push !

**Comment by mauriceAlthoff** [comment]
need's forther testing bud works for my examples

**Comment by ChrisKujawa** [comment]
nice also equal true und false geht bei mir gerad getestet ! Top!
