### ISSUE TITLE
support more than one function

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#168]
At this time we are support only one function 'main' we need to support other function and also function calls

**Comment by ChrisKujawa** [comment]
So hab deinen Bug jetzt gefixed :)

fuer das folgende Rail Programm:

<pre>
cat test/multiCharCommand/function/fail/s_func_test.rail 
$'main'(--):
 \
  \
   \
    \-------{test}--[SUCCESS]o--#
$'test'(--):
 \
  \
   \
    \-----{first}----{second}---#
$'first'(--):
 \
  \
   \
    \--[Hello]---#
$'second'(--):
 \
  \
   \
    \--o---#
</pre>

<pre>
$ javap -c Main.class 
public class Main {
  public static java.util.ArrayDeque stack;
  public Main();
    Code:
       0: aload_0       
       1: invokespecial #78                 // Method java/lang/Object."<init>":()V
       4: return        
  static {};
    Code:
       0: new           #54                 // class java/util/ArrayDeque
       3: dup           
       4: invokespecial #90                 // Method java/util/ArrayDeque."<init>":()V
       7: putstatic     #104                // Field stack:Ljava/util/ArrayDeque;
      10: return        
  public static void first();
    Code:
       0: getstatic     #104                // Field stack:Ljava/util/ArrayDeque;
       3: ldc           #110                // String Hello
       5: invokevirtual #92                 // Method java/util/ArrayDeque.push:(Ljava/lang/Object;)V
       8: return        
  public static void main(java.lang.String[]);
    Code:
       0: invokestatic  #112                // Method test:()V
       3: getstatic     #104                // Field stack:Ljava/util/ArrayDeque;
       6: ldc           #110                // String Hello
       8: invokevirtual #92                 // Method java/util/ArrayDeque.push:(Ljava/lang/Object;)V
      11: getstatic     #97                 // Field java/lang/System.out:Ljava/io/PrintStream;
      14: getstatic     #104                // Field stack:Ljava/util/ArrayDeque;
      17: invokevirtual #91                 // Method java/util/ArrayDeque.pop:()Ljava/lang/Object;
      20: invokevirtual #94                 // Method java/lang/Object.toString:()Ljava/lang/String;
      23: invokevirtual #79                 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
      26: return        
  public static void second();
    Code:
       0: getstatic     #97                 // Field java/lang/System.out:Ljava/io/PrintStream;
       3: getstatic     #104                // Field stack:Ljava/util/ArrayDeque;
       6: invokevirtual #91                 // Method java/util/ArrayDeque.pop:()Ljava/lang/Object;
       9: invokevirtual #94                 // Method java/lang/Object.toString:()Ljava/lang/String;
      12: invokevirtual #79                 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
      15: return        
  public static void test();
    Code:
       0: invokestatic  #115                // Method first:()V
       3: invokestatic  #117                // Method second:()V
       6: return        
}
</pre>

Ausgabe ist:

<pre>
Hello
Hello
</pre>

Daaas liegt aber noch am Constantpool Bug den du schonmal gemeldet hast!

**Comment by vincentbohlen** [comment]
krasse Sache. so schnell und ich stand da wie der esel vorm tor ._.

**Comment by ChrisKujawa** [comment]
:) next mal gleich fragen :) aber echt kuhl das das jetxt funktioniert wieder ein top ding was wir abhacken koennen sieht auch geil in der class datei aus :D
