### ISSUE TITLE
ASG nach Erstellung auf Fehler prüfen

### ISSUE THREAD

**Issue by mbaeten** [ccebinger/SWPSoSe14#170]
- Doppelte Funktionsnamen
- ---{foo}--- aber Funktion 'foo' existiert nicht
- korrupte csv files (werden von Haskell erzeugt):<br />
  [main]<br />
  1;v;0;2<br />
  2;#;0;0<br />
- ...

**Comment by leonbornemann** [comment]
Bei Doppelten Funktionsnamen schmeißt der Lexer jetzt ne warning(der Compiler läuft aber noch durch

**Comment by leonbornemann** [comment]
Bezüglich korrupte serialisierte files unterhalte ich mich heute mal mit haskell - mal sehen was wir da machen

**Comment by leonbornemann** [comment]
Das Einzige was hier laut Haskell passieren kann ist, dass beide Nachfolger 0 sind - das muss bei der Deserialisierung geprüft werden und in diesem Fall sollte eine Exception ausgegeben werden

**Comment by leonbornemann** [comment]
Ist jetzt erledigt, beim Testen ist mir aber aufgefallen dass eventuell beim deserialiseren noch nicht alle Funktionen deserialisiert werden? Habe mal ein neuen Issue aufgemacht:  #245
