### ISSUE TITLE
handle -1 of compareTo

### ISSUE THREAD

**Issue by kretzschi** [ccebinger/SWPSoSe14#171]
For the greater Method, we use compareTo in java/lang/Interger. It returns 1 (a > b), 0 (a = b) or -1 (a < b).
We have to think about how to handle the different possible results in bytecode.

**Comment by ChrisKujawa** [comment]
Ich wuerds einfach in eine 0 wandeln

**Comment by kretzschi** [comment]
Used primitive types!
