### ISSUE TITLE
Bytecode class documentation

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#174]

**Comment by kretzschi** [comment]
Verschiebe ich mal in MS3

**Comment by ccebinger** [comment]
Was ist hierbei genau zu tun?=

**Comment by ChrisKujawa** [comment]
1. Bin ich da dran siehe assignee
2. Find ichs nicht sinnvoll das du die doku machst, weil du dadran nicht gearbeitet hast

**Comment by ChrisKujawa** [comment]
done !
