### ISSUE TITLE
Serialisierung/Deserialisierung für die backend Gruppe anpassen

### ISSUE THREAD

**Issue by leonbornemann** [ccebinger/SWPSoSe14#175]
Das backend möchte, dass Variablennamen/Funktionsnamen/Konstanten in der graphs-Datenstruktur ohne die Klammern/Ausrufezeichen gespeichert werden, da sie so direkt darauf zugreifen können.

**Comment by mbaeten** [comment]
dafür gibt es bereits ein Ticket: #145
