### ISSUE TITLE
Add Stackmap to class file

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#179]

**Comment by ChrisKujawa** [comment]
http://chrononsystems.com/blog/java-7-design-flaw-leads-to-huge-backward-step-for-the-jvm

**Comment by ChrisKujawa** [comment]
http://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.7.4

**Comment by ChrisKujawa** [comment]
@kretzschi  wir muessen das Code Attribute anpassen... ''A method's Code attribute may have at most one StackMapTable attribute.''

**Comment by kretzschi** [comment]
Japp, ich schau mal rein.

**Comment by kretzschi** [comment]
Mal ein Beispiel für einen einfachen StackMapTable.
Folgende java-Datei wurde compiliert:
_[...]
int a = 78;
int b = 52;
boolean c = (a > b);
[...]_

Durch das Verzweigen, werden zwei stack frames erstellt, einer für den Fall, der der PC einfach "weiterläuft", der andere, falls gesprungen wird (wenn a <= b).

**StackMapTable: number_of_entries = 2
        frame_type = 253 /\* append _/
          offset_delta = 15
        locals = [ int, int ]
           frame_type = 64 /_ same_locals_1_stack_item */
          stack = [ int ]**

**append** bedeutet, dass der Operanden Stack leer ist und die locals wie im vorherigen StackFrame (+ die, die in dem Branch noch dazu kommen durch den Sprung).
**same_locals_1_stack_item** bedeutet, dass die locals wie im vorherigen StackFrame sind.

Das kann heikel werden.

**Comment by kretzschi** [comment]
http://cr.openjdk.java.net/~andrew/jdk6-hs17-merge/raw_files/old/src/share/vm/classfile/
Wie schon einmal zitiert, es schmerzt einfach nur, sich mit dem StackMapTable auseinanderzusetzen.

**Comment by kretzschi** [comment]
Bei Fehlern mit dem StackMapTable, class-Datei mit der Flag -XX:-UseSplitVerifier ausführen. Umsetzung kann nicht abgeschätzt werden und wird deshalb verworfen.
