### ISSUE TITLE
implement Variable tables

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#183]

**Comment by ChrisKujawa** [comment]
maybe the same #179 ?

**Comment by ChrisKujawa** [comment]
denke mit #186 hat sich das auch erledigt

**Comment by leonbornemann** [comment]
Sorry fürs ausgraben, soll das Frontend hier bereits Arbeit leisten(soweit möglich), und Variablen eintragen?

**Comment by leonbornemann** [comment]
Oh kann auch sein dass ich das Ticket mit der Symboltabelle verwechselt habe - wie ist da der Stand, soll da das Frontend noch zuarbeiten?

**Comment by ChrisKujawa** [comment]
das ist denke passé
