### ISSUE TITLE
Implement reading from System.in for Rail 'i' command

### ISSUE THREAD

**Issue by jdettlaff** [ccebinger/SWPSoSe14#185]

**Comment by jdettlaff** [comment]
Now correctly pushes (globalstack) an Integer if a digit is read.

**Comment by mbaeten** [comment]
Bitte nochmal evaluieren:
1. Das hier geht im Interpreter: echo "3" | rail-interpreter sourcefile.rail
2. system.in.read von der Console sollte auch gehen
3. Das Programm unten macht freude ;) Ne idee woran das liegt? _hust_ stackmap sucks _hust_

Rail-Programm:

<pre>
$ 'main' (--):
 \
  \---i-o---#
</pre>

<pre>
java test 
Exception in thread "main" java.lang.VerifyError: Expecting a stackmap frame at branch target 29
Exception Details:
  Location:
    test.main([Ljava/lang/String;)V @10: if_icmplt
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: b200 69b6 0056 3c1b 1030 a100 131b 1039
    0000010: a300 0d1b 1030 64b8 0058 a700 081b 92b8
    0000020: 0057 b200 6f5f b600 62b2 0068 b200 6fb6
    0000030: 0061 b600 64b6 0054 b1                 
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2531)
    at java.lang.Class.getMethod0(Class.java:2774)
    at java.lang.Class.getMethod(Class.java:1663)
    at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
ABRT problem creation: 'failure'
</pre>

**Comment by ChrisKujawa** [comment]
<pre> java -XX:-UseSplitVerifier test </pre>

http://stackoverflow.com/questions/15253173/how-safe-is-it-to-use-xx-usesplitverifier

Oder die nicht so schoene Variante:

<pre> java -noverify test </pre>

**Comment by mbaeten** [comment]
i try ;D

**Comment by mbaeten** [comment]
kk funzt, allerdings wird bei out noch println benutzt und ned print -.- Ich schreib Haskell mal ne mail

**Comment by ChrisKujawa** [comment]
Kann man ja leicht aendern:)
Am 28.06.2014 06:44 schrieb "SilverBln" notifications@github.com:
