### ISSUE TITLE
fix increment local variable bug

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#186]
the local variables are not increment anymore ...

**Comment by kretzschi** [comment]
Um dir Arbeit zu ersparen, hier die Methoden (die implementiert sind) und um wie viel diese den count hochzählen:

_output_Bytecode
// add 1
add_integer_calculation
// add 2
cut_ByteCode
// add 2
append_ByteCode
// add 2
false_ByteCode
// add 1
greater_ByteCode
// add 3
equal_ByteCode
// add 3
true_ByteCode
// add 1_

Vergiss den +1 nicht, wenn die main-Methode benutzt wird (durch das String[] Argument).

**Comment by ChrisKujawa** [comment]
Sauber danke :) ja naja das plus eins kann ich ja glei beim ctor setzen

**Comment by ChrisKujawa** [comment]
done
