### ISSUE TITLE
Fix gleiche Funtkionensnamen

### ISSUE THREAD

**Issue by leonbornemann** [ccebinger/SWPSoSe14#187]
Es werden vom Parser mehrere Funktionen mit gleichem Namen akzeptiert(ist mit Rail-Interpreter konform aber ziemlich unsinnig). Sollte also wahrscheinlich geprüft und gefixt werden, sodass das nichtmehr akzeptiert wird.

**Comment by mbaeten** [comment]
duplicate #170
