### ISSUE TITLE
Character Escaping in konstanten Strings implementieren

### ISSUE THREAD

**Issue by leonbornemann** [ccebinger/SWPSoSe14#188]
Hat eventuell mit #151 zu tun.

Rail gibt selbst vor welche Zeichen extra escapt werden müssen, siehe http://esolangs.org/wiki/Rail bei constants. Rail escaping funktioniert dabei anders als normales escaping:
\n entspricht in rail: \n\
Die Frage ist was mit anderen escapebaren ascii zeichen passieren soll: http://en.wikipedia.org/wiki/ASCII also z.B. \0 oder \b
Sollen die auch in der Railweise escapt werden oder normal? /discuss

**Comment by ChrisKujawa** [comment]
Warum sollte man \0 oder \b in einem String schreiben? Also sehe den Sinn gerade nicht^^ bzw ist es bei mir noch nie vorgekommen :D

**Comment by leonbornemann** [comment]
Naja könnte ja schonmal vorkommen, dass man halt das nullbyte schreiben will also \0 halt(z.B. wenn man iwas schreibt, was in c eingelesen werden soll und das da direkt mit drin sein soll oder so - ist sicherlich etwas weit hergeholt aber anwendungsfälle gibts schon)

**Comment by ChrisKujawa** [comment]
in Rail was schreiben was in C eingelesen werden soll ? :D

**Comment by leonbornemann** [comment]
Das rail-escaping sollte jetzt funktionieren, ob wir anderes escaping implementieren sprechen wir am besten heute mit der anderen Firma ab :)

**Comment by leonbornemann** [comment]
Erstmal closed. Um andere escapings mit der Haskell Gruppe abzusprechen mache ich ein anderes Ticket auf
