### ISSUE TITLE
Frontend-Parser: Verzweigungen implementieren

### ISSUE THREAD

**Issue by mbaeten** [ccebinger/SWPSoSe14#19]

**Comment by hanintalal** [comment]
ich habe den Code geschrieben aber mein Problem nun ist , dass ich nicht weiss genau wie ich das Program zum Laufen bringe,damit ich meinen Code pruefen kann ?
kann eine von euch ein klein Tipps im Readme File schreiben ?

**Comment by mbaeten** [comment]
Die Anleitung für Eclipse ist im git -> tutorials und funktioniert
einwandfrei mit Eclipse 3.8 (Juno) und 4.3.x (Kepler). Wenn das nicht
klappt, kannst du dich gerne nochmal bei mir melden.

Am 25.05.2014 17:16, schrieb hanintalal:
