### ISSUE TITLE
'?' type check command into Bytecode

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#190]
'?' Type? (a -- b) 
Returns 'string' or 'nil' or 'list' or 'lambda', depending on the type of the argument.
Pre:
Post: is_string(b)

**Comment by kretzschi** [comment]
@s0taka sitzt du da z.Z. dran ?

**Comment by vincentbohlen** [comment]
Mehr oder weniger. Habe vergessen mich rauszunehmen, nachdem du meintest, du wüsstest wies geht. Wenn du magst, können wir das auch zusammen machn. Musst mich nur briefen, wie du den typecheck benutzen willst.

**Comment by kretzschi** [comment]
Im Prinzip gibt es zwei Möglichkeiten.
1. Wir prüfen auf instanceof und geben dann den jeweiligen Typ zurück (wäre ein switch, aber ekelhaft zu bauen)
2. Wir nehmen getClass() müssen aber die Ausgabe evtl umbiegen (weil die Methode ja sowas wie _"class java.lang.String"_ zurück gibt)

**Comment by ChrisKujawa** [comment]
1. Waere sicher besser musste ja dann nur String.replace("java.lang.", "") machen

**Comment by kretzschi** [comment]
Japp, das meinte ich. Aber vielleicht steht Vincent ja aufs branchen xD. getClass() müsste auch schon im CP sein, sofern ich es nicht wieder rausgenommen habe.

**Comment by vincentbohlen** [comment]
Wollen wir uns einfach morgen (12-14?) oder Freitag zusammensetzen und das machen?
Ich habe jetzt in der Zwischenzeit angefangen die Abschlusspräso vorzubereiten.

**Comment by jdettlaff** [comment]
Ist es korrekt dass hier kein assignee (mehr?) drin ist? Falls ja, gebt's mir.

**Comment by kretzschi** [comment]
Tschuldige, hab nicht mitbekommen, dass Vincent sich rausgenommen hat. Stehe jetzt korrekt drin.

**Comment by kretzschi** [comment]
```
 $'main'(--):
  \
   \
    \
     \-[Hallo]?o---1?o--n?o--n1:?o--1-2:?o\
                                          |
                                          /
               ---------------------------
              /
              |
              /
  #--[aL]--&----\
                |
                |
                \---?o--#
```

Ausgabe:

```
 string
 string
 nil
 list
 list
 lambda
```
