### ISSUE TITLE
Bug: Strange behavior of add_if_then_else Method

### ISSUE THREAD

**Issue by kretzschi** [ccebinger/SWPSoSe14#192]
Hab jetzt mal das greater mit der besagten Methode aufgerufen. Mit javap kommt folgendes:
[...]
      47: istore_2  
      48: iload_1  
      49: iload_2  
      50: if_icmple     63
      53: iconst_1

Ist noch ok, aber dann:

```
    54: dstore_2      
    55: castore       
    56: aconst_null   
    57: nop           
    58: nop           
    59: nop           
    60: nop           
    61: goto          61
    64: nop           
    65: ladd          
    66: iconst_0      
    67: nop           
    68: nop           
    69: nop           
    70: nop           
    71: nop           
    72: nop           
    73: nop          
```

Können wir und ja morgen mal anschauen.

**Comment by ChrisKujawa** [comment]
Wtf jo ok

**Comment by ChrisKujawa** [comment]
<pre>
        50: if_icmple     57
        53: iconst_1      
        54: goto          58
        57: iconst_0      
        58: invokestatic  #81  
</pre>

Fixed! :+1:
