### ISSUE TITLE
Bug: List Testcases

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#193]
<pre>
':' Cons (a b -- c) 
c is a list cell with a == cdr(c) and b == car(c)
Pre: is_list(a)
Post: is_list(c) && ~is_nil(c)
'~' List breakup (a -- b c) 
b is cdr(a) and c is car(a)
Pre: is_list(a) && ~is_nil(a)
Post: is_list(b)</pre>

Das heisst fuer mich das Werte nur dann appended werden koennen wenn bereits eine List aufm Stack liegt .
(Die Beispiele im Esolang sind auch dem entsprechend gestaltet)
Dann stimmten aber die Testcases nicht...?

**Comment by tmichaelis** [comment]
Welche testf?lle den genau ?

Date: Thu, 26 Jun 2014 03:03:22 -0700

**Comment by ChrisKujawa** [comment]
s_cons_string.rail
s_breakup2.rail  
 s_cons_nums.rail

Breakup 1 hab ich schon geaendert

**Comment by tmichaelis** [comment]
Ich müsste das mal testen (habe gerade keine Möglichkeit), aber soweit ich das sehe sind die Fälle korrekt und laufen auch. Es muss keine leere Liste davor auf den stack gepusht werden.
Lg tomasz

Date: Thu, 26 Jun 2014 03:22:02 -0700

**Comment by ChrisKujawa** [comment]
Hm naja weil in der Spezifikation z.B. steht 
':' Cons (a b -- c) 
c is a list cell with a == cdr(c) and b == car(c)
Pre: is_list(a) 

was fuer mich heisst er prueft vorher ob a eine liste ist bzw wenn dir die Beispiele anguckst im esolang dann sind da auch leere liste vorher drauf.

**Comment by ChrisKujawa** [comment]
zb das Beispiel http://esolangs.org/wiki/Rail#Something_larger

**Comment by tmichaelis** [comment]
Ich glaub der Grund dafür dürfte folgender sein:

Es gibt in rail keine 2-elementigen Listen. Zb wenn du eine hast und ein Element rausnimmst, dann bleibt das letzte Element alleine auf dem Wrack und die Liste hat sich aufgelöst. Wenn du Algorithmen benutzt musst du ja prüfen, ob die Liste NIL ist. Das geht nur wenn du vorher ans Ende eine leere Liste angehängt hast, da du sonst kein Kriterium zum Prüfen hast

Date: Thu, 26 Jun 2014 03:41:39 -0700

**Comment by tmichaelis** [comment]
Sry meinte es gibt keine 1-elementigen Listen.

Date: Thu, 26 Jun 2014 03:41:39 -0700
