### ISSUE TITLE
Kompletter Sprachumfang im Frontend ? 

### ISSUE THREAD

**Issue by KosticS** [ccebinger/SWPSoSe14#194]
Testen welche Funktion ggf. noch im Frontend implentiert werden müssen. 
Das Issue #88 wurde aufgeteilt.

**Comment by hanintalal** [comment]
was it genau der Unterschied dazwischen und der" Test cases" ?
soll ich "test" schreiben oder einfach  jedes Befehl Probieren und, falls was schief gelaufen ist ,sag ich euch bescheid ?

**Comment by hanintalal** [comment]
@leonbornemann können wir morgen darüber an der Uni besprechen ?
