### ISSUE TITLE
Doxygen Doku zur Adjazenzliste

### ISSUE THREAD

**Issue by KosticS** [ccebinger/SWPSoSe14#197]

**Comment by ChrisKujawa** [comment]
Hab ich auch gemacht?!

**Comment by KosticS** [comment]
Sorry, hab ich dann auch gesehen.

Ich hab erst mal nur die Anweisung von Leon ausgeführt und zu allen 
Dateien ein Issue erstellt ;)

Am 26.06.14 16:34, schrieb Zelldon:
