### ISSUE TITLE
Typ-Vergleiche

### ISSUE THREAD

**Issue by mbaeten** [ccebinger/SWPSoSe14#212]
Bitte fixen

<pre>
'q' Is equal to (a b -- c) 
    [...] If a and b are of different types, then they are always unequal.
</pre>

Test-Datei:

<pre>test/builtInCommand/conditional/equal_num_string.rail</pre>

<pre>
Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
            at equal_num_string_cppCpp.main(Unknown Source)
        ABRT problem creation: 'success'
</pre>

**Comment by kretzschi** [comment]
Ja, der Typvergleich steht noch aus, ist aber irgendwie nicht so trivial, wie ich dachte. Bin aber dran

**Comment by mbaeten** [comment]
kk

**Comment by ChrisKujawa** [comment]
@kretzschi http://stackoverflow.com/questions/10162802/see-if-two-object-have-the-same-type 

<pre>
obj1.getClass().equals(obj2.getClass())
</pre>

Sollte doch funktionieren oder?

**Comment by kretzschi** [comment]
Japp, das Problem ist nur, dass ich keinen Branch aus dem dynamisch erzeugten Code von equals bauen kann. Außerdem habe ich gerade gesehen, dass ich ja erst nur für ints den equals Vergleich drin habe., was sich schnell ändern lässt, sofern invoke virtual mitspielt :D

**Comment by kretzschi** [comment]
Ach Kacke, ich weiß glaub ich, warum er immer beim invoken von equals "damals" nen Stack underflow geworfen hat ... mom, ich muss das noch überprüfen eben :D

**Comment by ChrisKujawa** [comment]
Haha alles klar

**Comment by kretzschi** [comment]
Ich könnte weinen, ich brauch gar nichts branchen, Java macht schon alles für mich .... :D Es war sooooooo einfach ... ;(
