### ISSUE TITLE
Parser ">" bitte mal evaluieren

### ISSUE THREAD

**Issue by mbaeten** [ccebinger/SWPSoSe14#213]
Testdatei dazu: test/builtInCommand/conditional/false.rail

Da sollte False rauskommen, es kommt aber True

**Comment by kretzschi** [comment]
@mauriceAlthoff bearbeitet das Ticket zur Zeit. Siehe #167 
Er zeigt True, weil wir zur Zeit alles noch "einebnen". Die f Funktion funktioniert soweit, habe ich gerade getestet.

**Comment by mbaeten** [comment]
kk

**Comment by mauriceAlthoff** [comment]
Junctions sind noch nicht fertig deswegen klappt das noch nicht

**Comment by leonbornemann** [comment]
Da das ne backend Sache ist schließe ich das Ticket mal wieder
