### ISSUE TITLE
Deserialisierung für Lambda anpassen

### ISSUE THREAD

**Issue by leonbornemann** [ccebinger/SWPSoSe14#218]
In der Deserialisierung muss Lambda erkannt werden, und zwar so, wie es gerade vom Parser dort hineingeschrieben wird.

**Comment by ChrisKujawa** [comment]
Was willste da anpassen ? Sollte genauso funktionieren wie es jetzt schon tut?

**Comment by leonbornemann** [comment]
Hier musste was angepasst werden, da der Lambda command string ja länger als 1 ist, also musste ein Fall hinzugefügt werden

**Comment by leonbornemann** [comment]
Bei der Gelegenheit ist mir aufgefallen, dass default mäßig, also wenn keiner der abgedeckten Fälle zutrifft, die in der getCommand-Methode abgefragt werden als Command-Type einfach Output zurückgegeben wird. Sollte man hier nicht lieber eine Exception werfen?
