### ISSUE TITLE
Bug: List append 

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#220]
append Bytecode should get a conditional to check if its a list or not if not then create new list and these two objects into

**Comment by kretzschi** [comment]
Kannst du das Problem nochmal kurz mit einem Beispiel erklären? Kann irgendwie keinen Fehler reproduzieren. :)

**Comment by ChrisKujawa** [comment]
<pre>
-----a--c--:---b---#
</pre>

**Comment by ChrisKujawa** [comment]
Wenn keine Liste aufm stack liegt funktioniert das nicht, deshalb checken ob liste da wenn nein dann liste erzeugen und beide Werte rein packen!

**Comment by kretzschi** [comment]
Okay, also: ----1---2:---# funktioniert jetzt. Daraus macht er: [1,2]
Aber: ----n----1:--# funktioniert nicht, weil er ausgibt: [1,[]]

Das liegt daran, dass du im conditional branch nochmal add aufrufst und dadurch scheinbar die leere - gerade erstellte - Liste pushst.

Er soll ja nur im Fall von -----1---2:--# eine neue Liste erstellen und die beiden Werte reinpushen. Wenn schon eine Liste existiert -----n--1:--# dann brauch er die Liste auch nicht pushen.

**Comment by jdettlaff** [comment]
Habs mit #235 zusammen gefixt.
