### ISSUE TITLE
Extra: Support negative numbers

### ISSUE THREAD

**Issue by kretzschi** [ccebinger/SWPSoSe14#221]
Sofern noch Zeit ist, wäre es schön, wenn wir Rail um negative Zahlen erweitern können. Wie wir es syntaktisch umsetzen würden, kann man ja mal bei Interesse diskutieren.

**Comment by jdettlaff** [comment]
Wir unterstützen sie ja bereits:
$ 'main'
 -13so#
Gibt "-2" aus, dank java/lang/Integer.

Auch:
$ 'main'
 -[-3]2ao#
Gibt "-1" aus.
Gibt es überhaupt andere Stellen, wo negative Zahlen gesondert behandelt werden müssen?

**Comment by kretzschi** [comment]
Aber bei deinem ersten Beispiel, das - ist doch eine Rail oder ? wie rafft er denn da, dass es ein minus sein soll?

Aber sonst ist das gut zu wissen :D

**Comment by mbaeten** [comment]
ist alles korrekt so.
---123--- ergibt auch 1,2,3
-1 etc geht nur mit [-1]

**Comment by jdettlaff** [comment]
Im ersten Beispiel wird +1, dann +3 gepusht, dann subtrahiert, was korrekt -2 ergibt. Im 2. Beispiel wird die negative Zahl (mit eckigen Klammern) ja auch richtig gepusht.

**Comment by kretzschi** [comment]
Achso, ja dann verstehe ich das! Top, dann schließe ich das mal wieder ;)
