### ISSUE TITLE
Error: Inconsistent stack height

### ISSUE THREAD

**Issue by kretzschi** [ccebinger/SWPSoSe14#235]
Nach dem ich den Bug für das "list append" fixen wollte, kam mir folgender Fehler unter:
**Fehlermeldung: Inconsistent stack height 3 != 2**

Grundlage war folgendes Rail Programm:
$'main'(--):
 \
  \
   \
     ---n-3:-o#

Auch bei:
$'main'(--):
 \
  \
   \
     ---1-3:-o#

Vielleicht der Fehler, weil ich zweimal in die gleiche "Variable" speichere (siehe ASTORE_1)?

**Comment by jdettlaff** [comment]
Accepted. Wird hoffentlich zum Daily fertig.

**Comment by kretzschi** [comment]
Danke fürs Akzeptieren. Bis zum Daily wär enorm !

**Comment by jdettlaff** [comment]
Zwischenbericht, mache weiter, aber als Notiz halb an mich selbst: 
Scheinbar liegt nach der conditional branch, die eine neue ArrayList erstellt (und jetzt auch das erste Element einfügt), mindestens ein Element mehr auf dem Operandenstack als wenn die branch nicht genommen wird.

**Comment by jdettlaff** [comment]
Done!
