### ISSUE TITLE
[Parser] Bug: Lambda hat kein successor

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#239]
Siehe z.B. test/multiCharCommand/lambda/lambda_down.rail

**Comment by ChrisKujawa** [comment]
Also ich habs mir mal weiter angesehen und anscheind wird kein successor angegeben wenn ein Lambda erkannt wird. Z.B. bei lambda_up

Sieht die main wie folgt aus:

[main]
1;&0;0,0
3;{};4,0
4;o;5,0

Erstens hat lambda in dem Beispiel dann kein succesor deshalb bricht die generierung ab zweitens fehler Node 2 ?

**Comment by leonbornemann** [comment]
Ich schaus mir an sollte hoffentlich schnell zu lösen sein, muss ein bug im Parser sein

**Comment by leonbornemann** [comment]
Also bei test/multiCharCommand/lambda/lambda_call_in_other_function.rail funktioniert alles (Der Ast ist korrekt und der Lambda Knoten hat einen Nachfolger) ich schau mir mal lambda_up im speziellen an.

**Comment by leonbornemann** [comment]
fixed
