### ISSUE TITLE
Frontend: Prüfen, was Lambda '&' ist

### ISSUE THREAD

**Issue by mbaeten** [ccebinger/SWPSoSe14#24]
Evtl Mail an Entwickler schicken

http://esolangs.org/wiki/Rail

**Comment by mbaeten** [comment]
Ich hab Jonathon Duerig am 28.0.5. eine entsprechende Mail geschickt, bis dato noch keine Antwort

**Comment by ChrisKujawa** [comment]
Hat Paul im Seminar erzaehlt. Wenn lambda also '&' auftaucht ist alles danach eine anonyme funktion.Man ruft diese funktion dann via {} auf. So habe ich es verstanden. LG chris

**Comment by tmichaelis** [comment]
Ja. Lambda funktioniert wie '@'. Nur alles was dahintersteht wird in eine closure gepackt (mit dem Namen der Funktion, in der man sich befindet). Sobald { } erreicht wurde, springt man hinter die Lambda Funktion (also hinter das '&') und bewegt sich dort weiter.

lg Tomasz

Date: Mon, 2 Jun 2014 10:18:58 -0700

**Comment by tmichaelis** [comment]
Ich hab paar Tests zu Lambda geschrieben u.a. eine verschachtelte Lambda Funktion.

**Comment by mbaeten** [comment]
Ein entsprechendes (optionales) Ticket für MS3 wurde erstellt: #95
