### ISSUE TITLE
Graphs unmarshall deserialisiert nur eine Funktion?

### ISSUE THREAD

**Issue by leonbornemann** [ccebinger/SWPSoSe14#245]
Beim testen von #170 ist mir aufgefallen dass anscheinend in der unmarshall Methode immer nur eine Funktion deserialisert wird, auch wenn mehrere in der Datei stehen.
Kann das jemand bestätigen, oder widerlegen, der vorher daran gearbeitet hat @Zelldon oder @SilverBln ?
Falls das der Fall ist kann sich jemand aus dem Frontend da ja mal ransetzen.

**Comment by ChrisKujawa** [comment]
Kann eig nicht sein da functionen via [ ] erkannt und deserialisiert werden

**Comment by leonbornemann** [comment]
Hmm also ich hab gerade einen Ast mit zwei Funktionen deserialisieren lassen, und nachdem er mit der ersten fertig war ist der Debugger auf jeden fall nichtmehr in die 'unmarshall_line' Methode reingesprungen, vielleicht lag das auch an was anderem, ich prüfs mal nochmal genauer nach

**Comment by ChrisKujawa** [comment]
Poste mal das Beispiel

**Comment by leonbornemann** [comment]
-------------Beginn Ast Datei nach dieser Zeile---------------------
[main]
1;[1];2,0
2;{hiho};3,0
3;o;4,0
4;#;0,0
[hiho]
1;[1];2,0
2;#;0,0
-------------Ende Ast-Datei---------------------
Ich glaube der Fehler liegt in 'skip_empty_lines' - Wenn ich eine leere Zeile vor [hiho] einfüge wird beides geparst.

**Comment by leonbornemann** [comment]
Ich würde mich da mal drum kümmern und da weiter nachforschen

**Comment by leonbornemann** [comment]
esseidenn du weißt sofort was es ist und kannst es direkt beheben

**Comment by ChrisKujawa** [comment]
Na du hast es doch gerad selber geschrieben was es ist ? :)

**Comment by leonbornemann** [comment]
Jo zumindest wo der Fehler liegen müsste ich fix es gleich.
