### ISSUE TITLE
Wrong target jump (branching)

### ISSUE THREAD

**Issue by kretzschi** [ccebinger/SWPSoSe14#248]
Hab gerade weiter an der Type Methode geschrieben und erhalte folgende Ausgabe bei javap:

```
    43: ifeq          48
    46: ldc           #142                // String string
    48: astore_1      
    49: aload_1       
    50: getstatic     #139  
```

Jedoch soll er nicht auf 48 springen, sondern auf 49. Der conditional_body sieht nämlich so aus:

```
code->add_ldc_string("string", first_conditional_body);
first_conditional_body.push_back(codegen::MNEMONIC::ASTORE_1);
```

Wenn er richtig springt, müsste es laufen.

Testdatei:

```
---3?--#
```

Erwartete Ausgabe:

```
string
```

**Comment by kretzschi** [comment]
Ach mist, ich muss ja noch pushen xD

**Comment by ChrisKujawa** [comment]
versuchs nochmal :)

**Comment by kretzschi** [comment]
Danke :+1:
