### ISSUE TITLE
Again: Inconsistent stack height 0 != 1

### ISSUE THREAD

**Issue by kretzschi** [ccebinger/SWPSoSe14#256]
In der _list_push_ tritt wieder der besagte Fehler auf.

z.B.

```
 ---n--1:-#
```

**Comment by jdettlaff** [comment]
Jo, hab nen Verdacht woran es liegt (s. #248). Wird gefixt sobald ich zu Hause bin heute abend.

**Comment by jdettlaff** [comment]
Mir war eh grad langweilig. Jo das wars. Fixed.
