### ISSUE TITLE
Verhalten von Junktions als Rails untersuchen 

### ISSUE THREAD

**Issue by KosticS** [ccebinger/SWPSoSe14#34]
Werden die Junktions < ,>, ^ und v auch als Rails verwendet oder nur als 'ifs' ?

**Comment by hanintalal** [comment]
ich habe sie als Verzweigung geschrieben ,das was  du meinst  oder was anderes?

**Comment by KosticS** [comment]
@ Hanin : Als Verzweigung ist schon richtig :) . Ich meinte etwas anderes. Du musst dir also keine Sorgen machen.
