### ISSUE TITLE
Backend: CP-counts implementieren

### ISSUE THREAD

**Issue by kretzschi** [ccebinger/SWPSoSe14#39]
Methoden zum Erfragen der Anzahl der Elemente im constant pool implementieren.
Beinhaltet folgende counts:
1. constant_pool_count
2. interfaces_count*
3. fields_count*
4. methods_count
5. attributes_count

*gibt es nicht in Rail

**Comment by mauriceAlthoff** [comment]
Funktion ist Implementiert. Sie heist:

size_t ConstantPool::countItemType(ItemType type) 

Die Typen sind wie folgt definiert:
enum ItemType{
  CLASS = 7,
  FIELD = 9,
  METHOD = 10,
  IMETHOD = 11,
  UTF8 = 1,
  STR = 8,
  INT = 3,
  LONG = 5
};
