### ISSUE TITLE
Fehler in class-File: Unknown constant tag 0 in class file

### ISSUE THREAD

**Issue by jdettlaff** [ccebinger/SWPSoSe14#46]
Exception in thread "main" java.lang.ClassFormatError: Unknown constant tag 0 in
 class file.
(Der erste Constantpool-Eintrag scheint tatsächlich mit einem nil-Byte zu starten).

**Comment by ChrisKujawa** [comment]
Also ich denke es fehlt auch die init methode sowie die access flags:

aus dem anderen Projekt ausm letzten Semester kann man denke einige anregungen mitnehmen ^^

https://github.com/swp-uebersetzerbau-ss13/javabite/blob/master/javabite-backend/src/main/java/swp_compiler_ss13/javabite/backend/classfile/Classfile.java

https://github.com/swp-uebersetzerbau-ss13/javabite/blob/master/javabite-backend/src/main/java/swp_compiler_ss13/javabite/backend/translation/Translator.java

**Comment by kretzschi** [comment]
Also die 'init' und die 'main' habe ich mal vor einiger Zeit (hart coded) implementiert, als der CP noch nicht soweit war - bis jetzt habe ich noch nicht prüfen können, ob der CP nun soweit ist ^^.
Das steht in der classfile_writer. Die 'init' ist in jeder class-file enthalten. Müsste auch fast immer - wenn nicht sogar immer - der gleiche Code sein.

Vielleicht hat Vincent schon näheres herausgefunden, er hat gestern noch im Daily gesagt, dass er sich das mal anschauen will.

**Comment by ChrisKujawa** [comment]
Jo das hab ich gesehen also eig muesste es ja auch drin stehen aber wenn ich mir jetzt zb ne class datei ansehen die ich per javac generiert habe dann sieht der anfang so aus:

<pre> 
0000000: cafe babe 0000 0033 0021 0a00 0700 190a  .......3.!......
0000010: 0003 001a 0700 1b07 001c 0a00 0400 1907  ................
0000020: 001d 0700 1e01 0006 3c69 6e69 743e 0100  ........<init>..
0000030: 0328 2956 0100 0443 6f64 6501 000f 4c69  .()V...Code...Li
</pre>

und unsere generierte: 

<pre>
0000000: cafe babe 0000 0033 0007 0010 6a61 7661  .......3....java
0000010: 2f6c 616e 672f 7379 7374 656d 0009 0014  /lang/system....
0000020: 6a61 7661 2e6c 616e 672e 7379 7374 656d  java.lang.system
</pre>

also iwie scheint da gewaltig was zu fehlen oder ?

Aber gut koenn das ja morgen frueh auch besprechen.

**Comment by kretzschi** [comment]
Also, kann es sein, dass bei deiner erstellten .class Datei (aus unserem Projekt) nach dem 'java/lang/system' ... 'java.lang.system.out' ... 'Java.io.printStream.println' ... 'Main.java' kommt? Ist das dann alles?
Es liegt wohl am Constant Pool. Der wird zwar in der classfile_writer geschrieben, aber die Methode (getByteArray) returnt lediglich die 'pool' Variable, ohne was zu schreiben.
Jetzt der Clou: Vorher wurde aber nichts in den Pool geschrieben, außer oben die vier Klassen/Methoden, die vom Konstruktor kommen.
Scheinbar wird die bytecode_generator übersprungen?! Habs noch nicht 100% durchblickt ...

**Comment by ChrisKujawa** [comment]
<pre> 
cafe babe - magic
0000 - minor version
0033 - major version J2SE7
0007 - CP This count is at least one greater than the actual number of entries!!!!! <=====
0010 - 1 <-------PROBLEM not exists TAG 0 
6a61 - 2
7661 - 3       6d61 696e - Hex for main is missing
2f6c - 4
616e - 5
672f - 6 -> Constantpool should end!
7379 7374 656d 0009 0014
6a61 7661 2e6c 616e 672e 7379 7374 656d
2e6f 7574 000a 001b 4a61 7661 2e69 6f2e
7072 696e 7453 7472 6561 6d2e 7072 696e
746c 6e00 0a00 094d 6169 6e2e 6a61 7661
0001 - access flag public
0010 - this class
5b48 - super class?
656c - interface count ?
6c6f 2057 6f72 6c64
5c6e 5c5d 0009 002a 6a61 7661 2f6c 616e
672f 5379 7374 656d 2e6f 7574 3a4c 6a61
7661 2f69 6f2f 5072 696e 7453 7472 6561
6d3b 000a 002f 6a61 7661 2f69 6f2f 5072
696e 7453 7472 6561 6d2e 7072 696e 743a
284c 6a61 7661 2f6c 616e 672f 5374 7269
6e67 3b29 5600 0000 0136 3637 3700 0000
0033 0001 0007 0008 0001 0009 0000 001d
0001 0001 0000 0005 2ab7 0001 b100 0000
0900 0b00 0c00 0100 0900 0000 2500 0200
0100 0000 09b2 0002 1203 b600 04b1 0000
</pre>

Also ich habe denke endlich diese Fehlermeldung verstanden :D 
Jeder eintrag aus dem Constantpool muss getagged werden damit die JVM weiss was fuer ein Eintrag das ist.

<pre>
 Typenbezeichnung | Wert  
CONSTANT_Utf8 | 1
CONSTANT_Unicode |  2
CONSTANT_Integer | 3
CONSTANT_Float | 4
CONSTANT_Long |  5
CONSTANT_Double | 6
CONSTANT_Class  | 7
CONSTANT_String | 8
CONSTANT_Fieldref | 9
CONSTANT_Methodref | 10
CONSTANT_InterfaceMethodref | 11
CONSTANT_NameAndType | 12
</pre>

Da es kein Tag mit 0 gibt wird dieser Fehlergeschmissen.

Quellen:

http://en.wikipedia.org/wiki/Java_class_file
http://www.fh-wedel.de/~si/seminare/ws07/Ausarbeitung/05.jvm/jvm3.htm
http://homepages.thm.de/~hg10013/Lehre/MMS/SS01_WS0102/JavaVM/classDateiformat.htm#Konstantenpool

**Comment by kretzschi** [comment]
Japp, das klingt plausibel.

Soweit ich mich erinnere, müsste der erste Eintrag eine CONSTANT_Methodref -> auf ein CONSTANT_Class -> auf java/lang/Object verweisen.

Und java/lang/Object taucht bei uns nun gar nicht in der class-file auf. Haben wir also schon mal einen Punkt, wo wir ansetzen können.

**Comment by ChrisKujawa** [comment]
Ja das problem ist das der falsche vector im classfile writer benutzt wird.
Ivh habs schon mal versucht bissel anzupassen zeigs dir nachher:)

**Comment by mauriceAlthoff** [comment]
Das Taggen mach ich doch indem ich zuerst 2 byte pushe mit diesem enum:
enum ItemType{
  CLASS = 7,
  FIELD = 9,
  METHOD = 10,
  IMETHOD = 11,
  UTF8 = 1,
  STR = 8,
  INT = 3,
  LONG = 5
};
hier eine Beispiel Methode dazu:
  Item i;
  size_t index = 0;
  i.set(value);
  if (!check(i)) {
    put2(LONG);
    index = put(i);
    putLong(value);
  } else {
    index = get(i).index;
  }
  return index;

**Comment by ChrisKujawa** [comment]
Ein Tag hat aber nur 1 Byte abgesehen davon  deine Push Methode reduziert von 32 auf 16 Bit ka ob sich das so gut verhaelt bzw was er da wirklich pushed.

**Comment by vincentbohlen** [comment]
Fehler behoben. Neue Fehler aufgetaucht. Resultat daraus sind die IMPORTANT issues.
