### ISSUE TITLE
BUG: writeVersionNumber Methode

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#55]
Ich hab in der Methode mal per Kommentar meine Loesungsmoeglichkeiten dazugeschrieben vllt kann sich das mal der Verantwortliche ansehen.

Ich hab hier das selbe Problem bei stackoverflow gefunden:
http://stackoverflow.com/questions/5966698/error-use-of-deleted-function

Einfache loesung waere einfach das const beim dem Array-type weg zulassen.

**Comment by jdettlaff** [comment]
Bitte schauen ob es jetzt bei dir kompiliert. Sehr seltsames Problem.

**Comment by ChrisKujawa** [comment]
Super compiliert :)
