### ISSUE TITLE
Mit -Wtype-limits kompilieren und die auftretenden Bugs lösen

### ISSUE THREAD

**Issue by jdettlaff** [ccebinger/SWPSoSe14#57]

**Comment by ChrisKujawa** [comment]
Maurice guck dir mal bitte den Constantpool an. Um genauer zu sein deine Vergleiche im UTF8 Encoding dort werden Warnings vom Compiler geschmissen das diese Vergleiche immer True ergeben.

**Comment by ChrisKujawa** [comment]
<pre>||=== Build: Debug in CBFrontEnd (compiler: GNU GCC Compiler) ===|
In member function ‘void ConstantPool::putUTF8(std::string)’:
|warning: comparison is always true due to limited |In member function ‘void ConstantPool::encodeUTF8(std::string, uint32_t)’:
warning: comparison is always true due to limited range of data type [-Wtype-limits]|
warning: comparison is always false due to limited range of data type [-Wtype-limits]|
|warning: comparison is always false due to limited range of data type [-Wtype-limits]|
||=== Build finished: 0 error(s), 4 warning(s) (0 minute(s), 13 second(s)) ===|
</pre>

**Comment by mauriceAlthoff** [comment]
Das sind falsche Warnungen der Compiler kommt nicht mit integer literals zurecht. Das muesste man mit einem Makro unterdruecken

**Comment by ChrisKujawa** [comment]
Dann mach das bitte :D dann sind wir die Warnungen auch los

**Comment by mbaeten** [comment]
"else if (c > 0x7FF)" mit uint8_t für c ist aber korrekt. das kann nie wahr werden. Wo ist da die meldung falsch? 0x7FF = 2047 dezimal und uint ist halt 2^8 = 0-255

**Comment by ChrisKujawa** [comment]
Btw 0xB1 ist 177 du willst aber auf 127 testen dann musst du 0x7f benutzen

**Comment by mbaeten** [comment]
Und unterdrück die Warnungen bitte nicht einfach. Wenns damit später Probleme geben sollte findet man genau solche Stellen nicht mehr. Dann lass lieber die Warnings drin bis wir das gründlichst durchleutet haben.

**Comment by mauriceAlthoff** [comment]
das testet ob es ein 1 , 2 oder 3 byte grosses zeichen ist und bei utf8 geht das erste byte von 0 - 7F, das zweite von 80 -  7FF und das dritte von 0800 - FFFF.
Es steht in den Kommentaren zwar die zahlen 1 bis 127 damit sind aber die utf8 zeichennummern gemeint. Also soll ich die Warnungen so lassen?

**Comment by mbaeten** [comment]
So jetzt hab ich begriffen, was du genau machen willst...
Um zu erfahren, wie viele bytes ein Unicode Zeichen in Utf-8 benötigt brauchst du aber auch nen Unicode Zeichen. Du vergleichst da aber nur ein byte. Das kann nicht klappen. Unicodes brauchen bis zu 4 bytes. Dein Check ist also trotzdem falsch und die Warnung korrekt.

Schau dir mal in common/Encoding.h die Funktion getRuneByteCount() an. Die bekommt ein uint32 (ein Unicode Zeichen) und dann klappt das auch.

**Comment by mauriceAlthoff** [comment]
An der einen Stelle war der Fehler richtig. Ich vergleiche jetzt mit dem iterator aber die Fehler die jetzt noch kommen Stammen daher das wir std::basic_string<char> string benutzen und daher nicht alle utf8 Symbole abdecken. Wenn wir std::wstring benutzen oder einen eigenen nutzen sind die vergleiche gültig.

Die 3 Warnungen die jetzt noch da sind können aber so bleiben.

**Comment by jdettlaff** [comment]
Habe jetzt zumindest mal die sehr simpel zu fixenden gefixt, die nervten so.
