### ISSUE TITLE
 Rail 'c' (cut) in JVM Bytecode umwandeln

### ISSUE THREAD

**Issue by kretzschi** [ccebinger/SWPSoSe14#62]
Teil-Issue zu #54

**Comment by ChrisKujawa** [comment]
<pre><code class="java">
/**
 *
 * @author Christopher Zell <zelldon91@googlemail.com>
 */
public class JavaByteCode {
  public static void main(String[] args) {
    String s = "1234";
    s.substring(0, 2);
    s.substring(2);
  }
}
public class javabytecode.JavaByteCode {
  public javabytecode.JavaByteCode();
    Code:
       0: aload_0       
       1: invokespecial #1                  // Method java/lang/Object."<init>":()V
       4: return        
  public static void main(java.lang.String[]);
    Code:
       0: ldc           #2                  // String 1234
       2: astore_1      
       3: aload_1       
       4: iconst_0      
       5: iconst_2      
       6: invokevirtual #3                  // Method java/lang/String.substring:(II)Ljava/lang/String;
       9: pop           
      10: aload_1       
      11: iconst_2      
      12: invokevirtual #4                  // Method java/lang/String.substring:(I)Ljava/lang/String;
      15: pop           
      16: return        
}
</code></pre>
