### ISSUE TITLE
BUG: Constantpool tag #1

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#64]
Wenn ich die  generierte out.class mit javap disassemblen will kommt folgender Fehler:

 javap -c out.class
Error:  error while reading constant pool for out.class: unexpected tag at #1: 0

**Comment by ChrisKujawa** [comment]
$ xxd out.class : 

0000000: cafe babe 0000 0033 0007 0010 6a61 7661  .......3....java
0000010: 2f6c 616e 672f 7379 7374 656d 0009 0014  /lang/system....
0000020: 6a61 7661 2e6c 616e 672e 7379 7374 656d  java.lang.system
0000030: 2e6f 7574 000a 001b 4a61 7661 2e69 6f2e  .out....Java.io.
0000040: 7072 696e 7453 7472 6561 6d2e 7072 696e  printStream.prin
0000050: 746c 6e00 0a00 094d 6169 6e2e 6a61 7661  tln....Main.java
0000060: 0001 0001 3200 0100 0131 0009 002a 6a61  ....2....1..._ja
0000070: 7661 2f6c 616e 672f 5379 7374 656d 2e6f  va/lang/System.o
0000080: 7574 3a4c 6a61 7661 2f69 6f2f 5072 696e  ut:Ljava/io/Prin
0000090: 7453 7472 6561 6d3b 000a 002f 6a61 7661  tStream;.../java
00000a0: 2f69 6f2f 5072 696e 7453 7472 6561 6d2e  /io/PrintStream.
00000b0: 7072 696e 743a 284c 6a61 7661 2f6c 616e  print:(Ljava/lan
00000c0: 672f 5374 7269 6e67 3b29 5600 0000 0137  g/String;)V....7
00000d0: 3738 3800 0000 0033 0001 0007 0008 0001  788....3........
00000e0: 0009 0000 001d 0001 0001 0000 0005 2ab7  .............._.
00000f0: 0001 b100 0000 0900 0b00 0c00 0100 0900  ................
0000100: 0000 2500 0200 0100 0000 09b2 0002 1203  ..%.............
0000110: b600 04b1 0000                           ......

**Comment by jdettlaff** [comment]
Siehe Ticket #46

**Comment by ChrisKujawa** [comment]
Dachte waere schon behoben wo ich die Email mal von dir bekommen habe ^^ dann schliesse ich mal dieses Ticket
