### ISSUE TITLE
implement add_ByteCode, sub_ByteCode, mult_ByteCode, div_ByteCode, mod_ByteCode

### ISSUE THREAD

**Issue by vincentbohlen** [ccebinger/SWPSoSe14#69]

**Comment by kretzschi** [comment]
Hat Chris meines Erachtens schon implementiert. Schau mal in die bytecode_generator. Da gibt es die Methoden add_ByteCode(...), sub_ByteCode(...) usw.

Schließe darum erst einmal das Ticket.
