### ISSUE TITLE
Fehlermeldungen des Parsers auf stderr ausgeben(statt Standardausgabe)

### ISSUE THREAD

**Issue by leonbornemann** [ccebinger/SWPSoSe14#70]

**Comment by mbaeten** [comment]
Dafür dann bitte /src/common/Status.h verwenden

**Comment by mbaeten** [comment]
Mit Editor-Gruppe abgesprochen und bereits umgesetzt:
- Warnings auf std::cout
- Errors auf std::cerr
- Exceptions auf std::cerr
