### ISSUE TITLE
Adjust checkForValidCommandsInStraightDir

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#73]
<pre>switch(charAtStraight) {
        case 'o':
            setRowCol(straightRow, straightCol);
            addToAbstractSyntaxGraph("o", Command::Type::OUTPUT);
            break;
        case '[':
            setRowCol(straightRow, straightCol);
            //TODO: ueberpruefen ob notwendig: list<char> invalidCharList = {'[','{','(',},;
            addToAbstractSyntaxGraph(readCharsUntil(']'), Command::Type::PUSH_CONST);
            //TODO: create pushNode in graph
            break;
        case ']':
            setRowCol(straightRow, straightCol);
            addToAbstractSyntaxGraph(readCharsUntil('['), Command::Type::PUSH_CONST);
            break;
[...]
</pre>

kann z.B. angepasst werden auf:

<pre>
  setRowCol(straightRow, straightCol);
  addToAbstractSyntaxGraph(charAtStraight, (Command::Type) charAtStraight)
</pre>

So spart man sich die While wie ich das vorhin meinte.

Lg Chris

**Comment by mbaeten** [comment]
wont-fix ;)
