### ISSUE TITLE
Backend: Rail 'g' (greater) implementieren

### ISSUE THREAD

**Issue by kretzschi** [ccebinger/SWPSoSe14#74]

**Comment by kretzschi** [comment]
Done

**Comment by kretzschi** [comment]
Unfortunately, I forgot the typecheck, but the typecheck depends on ticket #123

**Comment by kretzschi** [comment]
Habe gerade typecheck eingebaut, nun bekomme ich folgenden Fehler:

Exception in thread "main" java.lang.VerifyError: Expecting a stackmap frame at branch target 50
Exception Details:
  Location:
    Main.main([Ljava/lang/String;)V @50: if_icmple
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: b200 4512 47b8 003a b600 42b2 0045 1248
    0000010: b800 3ab6 0042 b200 45b6 0041 c000 27b6
    0000020: 003b 3cb2 0045 b600 41c0 0027 b600 3b3d
    0000030: 1b1c a400 0000 6104 a700 0000 6103 e9b2
    0000040: 0045 124a b600 42b2 0044 b200 45b6 0041
    0000050: b600 43b6 0039 b1

**Comment by ChrisKujawa** [comment]
http://stackoverflow.com/questions/15122890/java-lang-verifyerror-expecting-a-stackmap-frame-at-branch-target-jdk-1-7

**Comment by kretzschi** [comment]
Hab ich auch schon gelesen, aber ist es die Lösung die JVM anzupassen? Muss mir demnächst die StackMap mal genauer anschauen.

**Comment by ChrisKujawa** [comment]
nee eher die stackmap impl.

**Comment by kretzschi** [comment]
I hate this ticket!!!

**Comment by ChrisKujawa** [comment]
haha top :dancer:
