### ISSUE TITLE
String and int distinction

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#76]
Moin Jonas,

wir hatten ja am Montag im TS darueber geredet das wir das nur mit Strings alles machen koennen.

Ich hab eventuell eine alternative gefunden mithilfe von instanceof (c1)*
Wir koennen wenn wir die Konstanten pushen( im Compiler) pruefen ob das arg jetzt ein int ist oder string und pushen je nachdem das richtige auf den Stack.

Wenn jetzt eine arithmetische operation kommt rechnen wir einfach die Integer zusammen ohne zu casten (wenn ein arg ein String ist crashed es, genauso wie in der Rail spec) 
Wenn wir jetzt Strings appenden wollen, koennen wir einfach pruefen ob es sich um ein String handelt via instanceof. Falls nicht rufen wir z.B. einfach Integer.toString(i) auf.

Das ermoeglicht uns dann spaeter auch korrekte Listen zu unterstuetzen und somit muessen wir nicht den kram mit den semikolon seperierten Strings machen.

Also hast du einwende?

LG Chris 

*http://docs.oracle.com/javase/specs/jvms/se7/jvms7.pdf SEITE 472

**Comment by jdettlaff** [comment]
Klingt gut. Wir müssen dann allerdings Integer pushen (nicht int!!), da 
instanceof immer Objektreferenzen bekommt. Und vor arithmetischen Ops 
die Integer zu int unboxen mit Integer#intValue().

Am 03.06.2014 20:42, schrieb Zelldon:

**Comment by ChrisKujawa** [comment]
Jo das stimmt aber das ist denke ich besser als alles mit Strings zu machen.

ODER:

man prueft nur auf String und wenns kein String war (ergo int was keine referenz hat) gibt instanceof 0 zurueck. Oder meinste das funzt nicht?

**Comment by jdettlaff** [comment]
Objektreferenzen und sonstige Dinge sind auf dem Operandenstack von 
außen nicht zu unterscheiden. Man muss selbst wissen, was draufliegt.

Am 03.06.2014 21:19, schrieb Zelldon:

**Comment by ChrisKujawa** [comment]
Ja das ist mir klar naja is auch egal dann machen wir das so mit den Wrapper Klassen wuerde ich sagen.

**Comment by jdettlaff** [comment]
Hi, das wird erst bei Listen interessant, die eh Referenzen sind. Wie 
auch Strings und alle Object-Referenzen aufm Operandenstack. Wir haben 
keine Wahl, die Referenzarchitektur ist von der JVM eh vorgegeben.

Ich sehe auch nicht so recht, wo wir da Spielraum hätten? Und wodurch 
genau wir "unfassbar viel RAM" sparen?

Am 03.06.2014 21:24, schrieb SilverBln:

**Comment by ChrisKujawa** [comment]
http://docs.oracle.com/javase/specs/jvms/se7/html/jvms-6.html#jvms-6.5.instanceof 

Jonas hast du ne Idee wie ich an den index im constant pool komme?

EDIT: hat sich denke erledigt

**Comment by jdettlaff** [comment]
Dafür muss halt eine Klassenreferenz (java/lang/String bzw. 
java/lang/Integer) im Constant Pool sein, wie du die bekommst frag halt 
Maurice oder guck in die Doku vom Constant Pool.

**Comment by ChrisKujawa** [comment]
Wie bereits da steht hat es sich erledigt...habs ja jetzt umgesetzt...

**Comment by jdettlaff** [comment]
Ach. Hehe. Guten Morgen. Ich bin wieder da.

**Comment by jdettlaff** [comment]
Ist dies jetzt komplett erledigt?

**Comment by ChrisKujawa** [comment]
ja also im grunde existieren jetzt methoden zu unterscheidung die muessen dann nur verwendet werden ordentlich :D 

ich schliesse damit mal das ticket
