### ISSUE TITLE
Backend: Listen implementieren

### ISSUE THREAD

**Issue by mbaeten** [ccebinger/SWPSoSe14#83]

**Comment by ChrisKujawa** [comment]
<pre>
$'main'(--):
 \
  \
   \---n[one]:[two]:[three]:---o---#
</pre>

Compiliert und gibt folgenden Output:

<pre>
$ java Main
[one, two, three]
</pre>

**Comment by ChrisKujawa** [comment]
<pre>
$'main'(--):
 \
  \
   \---n1:2:[one]:[two]:[three]:---o---#
</pre>

<pre>
[1, 2, one, two, three]
</pre>

**Comment by ChrisKujawa** [comment]
<pre>
':' Cons (a b -- c) 
c is a list cell with a == cdr(c) and b == car(c)
Pre: is_list(a)
Post: is_list(c) && ~is_nil(c)
'~' List breakup (a -- b c) 
b is cdr(a) and c is car(a)
Pre: is_list(a) && ~is_nil(a)
Post: is_list(b)</pre>

Das heisst fuer mich das Werte nur dann appended werden koennen wenn bereits eine List aufm Stack liegt .
(Die Beispiele im Esolang sind auch dem entsprechend gestaltet)
Dann stimmten aber die Testcases nicht...?

**Comment by ChrisKujawa** [comment]
done
