### ISSUE TITLE
Testautomatisierung

### ISSUE THREAD

**Issue by mbaeten** [ccebinger/SWPSoSe14#96]
Bei einem neuen Commit ins Repository sollen automatisch Tests ausgeführt werden:
- Kompilieren des Projekts und Build des Compilers
- Ausführen des Compilers mit Rail-Testprogrammen

**Comment by mbaeten** [comment]
Meine Anforderung daran sind:
- UnitTests müssen eigenständig sein (eigenständiges Projekt, im github ofc, Ordner ist schon angelegt)
- In dem eigentständigen Projekt dürfen UnitTest-Libraries verwendet werden, solange sie Open Source und Cross-Plattform sind (und möglichst leichtgewichtig). Bitte auch auf die Lizenz achten!
- Wenn ihr entsprechende Libs verwendet, schreibt bitte auch eine kleine allgemeine Anleitung, wie man euer Projekt zum laufen kriegt.

**Comment by hanintalal** [comment]
vielleicht hift Testautomatesierung "open source Framework " wie http://robotframework.org

**Comment by mbaeten** [comment]
Das Thema wurde bereits mit der Haskell Gruppen abgesprochen und ist schon in der "Produktion". Trotzdem interessant, danke ;)

**Comment by tmichaelis** [comment]
Der Stand ist, dass die Haskell Gruppe bereits so weit damit fortgeschritten ist, dass sie das ganze übernimmt.

lg Tomasz

Date: Mon, 23 Jun 2014 04:24:42 -0700

**Comment by mbaeten** [comment]
Wir bauen das trotzdem selber mit Java, da bei uns kaum jemand gut in shell scripting ist und wir gerne mehr Kontrolle über das Sub-Projekt hätten.

**Comment by mbaeten** [comment]
Zusätzlich interpretiere ich das Ticket mal um und sage, dass das später Jenkins betrifft, also mich. Das eigentliche Ticket für die Tests ist hier: #94

**Comment by mbaeten** [comment]
läuft und ist im jenkins. haskell muss meinen pull request noch akzeptieren, dann ist alles durch
